import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
	return (
		<div>
			<Head>
				<title>DCI Kaplong</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<h1>welcome to Deliverance Church International Kaplong </h1>
			</main>

			<footer></footer>
		</div>
	);
}
